# Generated by Django 6.0.2 on 2026-02-07 17:56

import django.contrib.postgres.fields
import metablux_internal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('company_id', models.TextField(unique=True)),
                ('company_cc_id', models.TextField(blank=True, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to=metablux_internal.models.logostorage)),
                ('verticals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True)),
                ('leadsource', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_book', models.JSONField(blank=True, null=True)),
                ('contact_book', models.JSONField(blank=True, null=True)),
                ('market_details', models.JSONField(blank=True, null=True)),
                ('arc', models.JSONField(blank=True, null=True)),
                ('First_contact', models.TextField(blank=True, null=True)),
                ('pt_key', models.CharField(blank=True, max_length=2000, null=True)),
                ('master_workspace_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_limit', models.IntegerField(blank=True, default=50, null=True)),
            ],
            options={
                'db_table': 'Company_profile',
            },
        ),
        migrations.CreateModel(
            name='MasterWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('unique_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.TextField()),
                ('setting_one', models.JSONField(blank=True, default=dict, null=True)),
                ('setting_two', models.JSONField(blank=True, default=dict, null=True)),
                ('setting_three', models.JSONField(blank=True, default=dict, null=True)),
                ('setting_four', models.JSONField(blank=True, default=dict, null=True)),
                ('setting_five', models.JSONField(blank=True, default=dict, null=True)),
                ('master_workspace_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'projects_adminpanel',
            },
        ),
    ]
